include:
    - "./proxy.yaml"

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 

services:
  db:
    image: mysql:8
    container_name: mysql
    ports: ["3306:3306"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    networks:
        backend:
            ipv4_address: 172.20.0.10

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.python
    <<: [*deploy-dev, *env_file, *restart]
    depends_on: ["db"]
    ports: ["5000:5000"]
    networks:
        backend:
            ipv4_address: 172.20.0.5