FROM python:3.12-slim as builder

WORKDIR /app

#Установка компилятора gcc
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc


RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

COPY requirements.txt ./

# Монтирование кеша pip с docker host
RUN --mount=type=cache,target=~/.cache/pip pip install -r requirements.txt

# RUN source /app/.env
RUN rm -rf /app/.env

FROM python:3.12-slim as worker
WORKDIR /app

RUN addgroup --system python && \
    adduser --system --disabled-password  --ingroup python python && chown python:python /app
USER python

COPY --chown=python:python --from=builder /app/venv ./venv
COPY --chown=python:python . .

ENV PATH="/app/venv/bin:$PATH"
# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 